name: Cria Infra do Terraform

on:
  workflow_dispatch:

jobs:
  plan:
    uses: FabioBartoli/linuxtips-terraform-reusable/.github/workflows/terraform-plan.yml@main
    with:
      working-directory: ./iac
    secrets: 
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}