name: Cria Infra do Terraform

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    uses: FabioBartoli/linuxtips-terraform-reusable/.github/workflows/terraform-plan.yml@main
    with:
      working-directory: ./iac
    secrets: 
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

  apply:
    needs: plan
    if: ${{ jobs.plan.conclusion == 'success' }}
    environment: tfapprove
    uses: FabioBartoli/linuxtips-terraform-reusable/.github/workflows/terraform-apply.yml@main
    with:
      working-directory: ./iac
    secrets: 
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}